# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Punch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Punch

  pod 'AFNetworking', '~> 3.0'
  pod 'Masonry'

end
